
'use client';

import { useContext, useState } from 'react';
import { BlogList } from '@/components/blog/BlogList';
import { getBlogPosts } from '@/lib/data';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useFirebase } from '@/firebase';
import { ArrowRight, BrainCircuit, Newspaper, PlayCircle, X, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import Image from 'next/image';
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '@/components/ui/carousel';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useTranslation } from '@/hooks/use-translation';


const videos = [
  {
    title: 'Personalized Career Roadmaps',
    description: 'See how our AI creates a unique path for every student.',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwbGFubmluZyUyMHNlc3Npb258ZW58MHx8fHwxNzY3Mjc0MTAxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'planning session',
    isVideo: false,
  },
  {
    title: 'Parent & Student Alignment',
    description: 'Discover careers together and get on the same page.',
    imageUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxzdHVkZW50cyUyMHRhbGtpbmd8ZW58MHx8fHwxNzY3MDk2MDI4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'students talking',
    isVideo: false,
  },
  {
    title: 'Powered by Gemini AI',
    description: "See a demo of how our career reports are generated by Google's advanced AI.",
    videoUrl: '/videos/careerraah-promo.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1695026931453-279a0717b070?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxnZW1pbmklMjBhaXxlbnwwfHx8fDE3MjI0NTMzNTZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'gemini ai',
    isVideo: true,
  },
  {
    title: 'Exploring Modern Careers',
    description: 'Learn about emerging fields beyond traditional choices.',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0ZWNoJTIwdGVhbXxlbnwwfHx8fDE3NjcyNzQxMDF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'tech team',
    isVideo: false,
  },
  {
    title: 'AI-Powered Assessments',
    description: 'Understand strengths and weaknesses with our expert AI.',
    imageUrl: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxhcmRpZmljaWFsJTIwaW50ZWxsaWdlbmNlfGVufDB8fHx8MTc2NzA5NjExOXww&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'artificial intelligence',
    isVideo: false,
  },
];

export default function Home() {
  const posts = getBlogPosts();
  const { t } = useTranslation();
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const { user } = useFirebase();
  const router = useRouter();

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim()) return;

    const returnPath = `/search-results?q=${encodeURIComponent(searchQuery)}`;
    // If we have a user, go directly there. Otherwise login first.
    // Note: checks against 'user' might be async, but for a simple button click this is usually fine 
    // if the auth state has settled. If auth is loading, 'user' is null, so it defaults to login flow which is safe.
    if (user) {
      router.push(returnPath);
    } else {
      router.push(`/login?returnPath=${encodeURIComponent(returnPath)}`);
    }
  };

  const featuredPosts = posts.filter(post => ['10', '16', '14'].includes(post.id));

  const handleCardClick = (video: (typeof videos)[0]) => {
    if (video.isVideo && 'videoUrl' in video) {
      setVideoUrl(video.videoUrl || null);
    } else if ('imageUrl' in video) {
      window.open(video.imageUrl, '_blank');
    }
  };


  return (
    <div className="flex flex-col min-h-screen fade-in">
      <main className="flex-grow">
        <section className="relative h-auto min-h-[600px] flex items-center justify-center text-center text-white py-16">
          <Image
            src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxzdHVkZW50cyUyMGxlYXJuaW5nfGVufDB8fHx8MTc2NzA5NjAyOHww&ixlib=rb-4.1.0&q=80&w=1080"
            alt="Supportive parent helping their child with career planning on a laptop"
            fill
            className="object-cover"
            data-ai-hint="parent child career"
            priority
          />
          <div className="absolute inset-0 bg-black/60" />
          <div className="relative z-10 p-4 space-y-12">

            <div>
              {/* Ask Anything Search Box */}
              {/* Ask Anything Search Box */}
              <div className="max-w-xl mx-auto mb-10 relative z-20">
                <p className="mb-6 text-xl md:text-2xl font-bold text-white drop-shadow-md tracking-wide">
                  Ask about your dream Job, College, or School 🎓
                </p>
                <form onSubmit={handleSearch} className="relative flex items-center w-full shadow-2xl rounded-full overflow-hidden bg-white/10 backdrop-blur-md border border-white/30 transition-all hover:bg-white/20 focus-within:bg-white/90 group">
                  <Search className="absolute left-4 w-6 h-6 text-white/70 group-focus-within:text-purple-600" />
                  <Input
                    placeholder="e.g. How do I get into Harvard? or What does a pilot do?"
                    className="w-full pl-12 pr-32 py-8 text-lg bg-transparent border-none text-white placeholder:text-white/60 focus-visible:ring-0 focus-visible:ring-offset-0 group-focus-within:text-gray-900"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    suppressHydrationWarning
                  />
                  <Button
                    type="submit"
                    className="absolute right-1 top-1 bottom-1 rounded-full px-6 font-semibold transition-all hover:scale-105"
                    style={{ backgroundColor: '#8B5CF6', color: 'white' }}
                    suppressHydrationWarning
                  >
                    Try Mentor
                  </Button>
                </form>
                <p className="mt-2 text-sm text-white/70">✨ Use our magical AI to explore your dream career</p>
              </div>

              <div>
                <h1 className="text-2xl md:text-3xl font-headline font-bold tracking-tighter text-white">
                  {t('home_hero_title')}
                </h1>
                <p className="mt-4 max-w-2xl mx-auto text-base text-white/90 mb-12">
                  {t('home_hero_subtitle')}
                </p>
              </div>
              <div className="mt-8 flex justify-center">
                <Button asChild size="lg" style={{ backgroundColor: '#FF6B00', color: 'white' }}>
                  <Link href="/login">
                    {t('home_hero_cta')} <ArrowRight className="ml-2" />
                  </Link>
                </Button>
              </div>
            </div>

            <div className="bg-black/20 backdrop-blur-sm p-8 rounded-2xl border border-white/20">
              <h2 className="text-2xl font-headline font-bold tracking-tight text-white">{t('home_parent_title')}</h2>
              <p className="mt-2 max-w-2xl mx-auto text-base text-white/90 font-semibold">
                {t('home_parent_tagline')}
              </p>
              <div className="mt-6 flex justify-center">
                <Button asChild size="lg" style={{ backgroundColor: '#FF6B00', color: 'white' }}>
                  <Link href="/parent-explorer">{t('home_parent_cta')}</Link>
                </Button>
              </div>
            </div>
          </div>
        </section>

        <section className="py-12 md:py-20 bg-background text-center">
          <div className="container mx-auto px-2 md:px-6">
            <h2 className="text-3xl font-bold font-headline tracking-tighter text-foreground sm:text-4xl">{t('home_why_title')}</h2>
            <div className="mt-8 max-w-5xl mx-auto">
              <Carousel
                opts={{
                  align: 'start',
                  loop: true,
                }}
                className="w-full"
              >
                <CarouselContent>
                  {videos.map((video, index) => (
                    <CarouselItem key={index} className="md:basis-1/2">
                      <div
                        className="relative aspect-video rounded-xl overflow-hidden shadow-2xl group cursor-pointer m-2"
                        onClick={() => handleCardClick(video)}
                      >
                        <Image
                          src={(video.isVideo ? video.thumbnailUrl : video.imageUrl) || ''}
                          alt={video.title}
                          data-ai-hint={video.imageHint}
                          fill
                          className="object-cover transition-transform duration-300 group-hover:scale-105"
                        />
                        <div className="absolute inset-0 bg-black/40 flex flex-col items-center justify-center p-4 text-center">
                          <PlayCircle className="w-16 h-16 text-white/80 transition-transform duration-300 group-hover:scale-110" />
                          <h3 className="mt-4 text-lg font-bold text-white">{video.title}</h3>
                          <p className="mt-1 text-xs text-white/90">{video.description}</p>
                        </div>
                      </div>
                    </CarouselItem>
                  ))}
                </CarouselContent>
                <CarouselPrevious className="left-2 sm:left-[-50px]" />
                <CarouselNext className="right-2 sm:right-[-50px]" />
              </Carousel>
            </div>
          </div>
        </section>

        {videoUrl && (
          <Dialog open={!!videoUrl} onOpenChange={(isOpen) => !isOpen && setVideoUrl(null)}>
            <DialogContent className="max-w-4xl p-0 border-0 bg-transparent">
              <DialogHeader>
                <DialogTitle className="sr-only">Video Player</DialogTitle>
              </DialogHeader>
              <video src={videoUrl} controls autoPlay className="w-full rounded-lg" />
            </DialogContent>
          </Dialog>
        )}

        <section id="featured-posts" className="py-12 md:py-20 bg-secondary/50">
          <div className="container mx-auto px-4 md:px-6">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold font-headline tracking-tighter text-foreground sm:text-4xl">{t('home_guides_title')}</h2>
              <p className="mt-3 max-w-2xl mx-auto text-muted-foreground md:text-xl">
                {t('home_guides_subtitle')}
              </p>
            </div>
            <BlogList posts={featuredPosts} showSearch={false} />
            <div className="text-center mt-12">
              <Button asChild size="lg">
                <Link href="/blog">
                  Explore All Guides <ArrowRight className="ml-2" />
                </Link>
              </Button>
            </div>
          </div>
        </section>

        <section className="py-12 md:py-20 bg-background">
          <div className="container mx-auto px-4 md:px-6 text-center">
            <h2 className="text-3xl font-bold font-headline tracking-tighter text-foreground sm:text-4xl">{t('home_plan_title')}</h2>
            <p className="mt-3 max-w-2xl mx-auto text-muted-foreground md:text-xl">
              {t('home_plan_subtitle')}
            </p>
            <div className="mt-8">
              <Button asChild size="lg">
                <Link href="/login">
                  {t('home_plan_cta')} <ArrowRight className="ml-2" />
                </Link>
              </Button>
            </div>
          </div>
        </section>

      </main>
    </div>
  );
}
