'use client';

import { useState, useTransition } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Loader2, Clapperboard, Wand2 } from 'lucide-react';
import { getVideoAction } from '@/lib/actions';
import { useToast } from '@/hooks/use-toast';

export default function VideoGeneratorPage() {
  const { toast } = useToast();
  const [prompt, setPrompt] = useState(
    "An animated, futuristic orange bridge made of glowing light-particles self-assembles across a dark, wide chasm. The bridge should look high-tech and stable. As it forms, animated icons for 'Coding', 'Logic', and 'Communication' appear and embed themselves onto the surface of the bridge. The style is inspiring and empowering."
  );
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const handleSubmit = () => {
    if (!prompt.trim()) {
      toast({
        variant: 'destructive',
        title: 'Prompt is empty',
        description: 'Please enter a description for the video you want to generate.',
      });
      return;
    }

    setVideoUrl(null);

    startTransition(async () => {
      const result = await getVideoAction(prompt);

      if (result.error) {
        toast({
          variant: 'destructive',
          title: 'Video Generation Failed',
          description: result.error,
        });
      } else if (result.videoUrl) {
        setVideoUrl(result.videoUrl);
        toast({
          title: 'Video Generated!',
          description: 'Your video is ready to be viewed.',
        });
      }
    });
  };

  return (
    <div className="container mx-auto max-w-2xl py-8 px-4 md:px-6 lg:py-12 fade-in">
      <Card className="shadow-2xl">
        <CardHeader>
          <div className="flex items-center gap-3">
             <Clapperboard className="h-10 w-10 text-primary" />
            <div>
                <CardTitle className="text-3xl font-headline font-bold">AI Video Generator</CardTitle>
                <CardDescription>Describe the video you want to create with AI.</CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          <Textarea
            value={prompt}
            onChange={e => setPrompt(e.target.value)}
            placeholder="e.g., A majestic dragon soaring over a mystical forest at dawn."
            rows={5}
            disabled={isPending}
            className="text-base"
          />
          <Button onClick={handleSubmit} disabled={isPending} size="lg" className="w-full" style={{ backgroundColor: '#FF6B00', color: 'white' }}>
            {isPending ? (
              <>
                <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                Generating Video (this may take a minute)...
              </>
            ) : (
              <>
                <Wand2 className="mr-2 h-5 w-5" />
                Generate Video
              </>
            )}
          </Button>
          
          <div className="mt-6">
            {isPending && (
                <div className="w-full aspect-video bg-muted rounded-lg flex flex-col items-center justify-center text-muted-foreground">
                    <Loader2 className="h-12 w-12 animate-spin text-primary mb-4" />
                    <p className="font-semibold">Your video is being generated by Veo...</p>
                    <p className="text-sm">This process can take up to 2 minutes. Please wait.</p>
                </div>
            )}
            {videoUrl && (
              <video
                src={videoUrl}
                controls
                autoPlay
                loop
                className="w-full aspect-video rounded-lg bg-black shadow-lg"
              >
                Your browser does not support the video tag.
              </video>
            )}
            {!isPending && !videoUrl && (
                 <div className="w-full aspect-video bg-muted/50 border-2 border-dashed rounded-lg flex flex-col items-center justify-center text-muted-foreground">
                    <p>Your generated video will appear here.</p>
                </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
